/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pageui;

/**
 *
 * @author ASUS
 */
public class HalamanUI extends javax.swing.JPanel {

    /**
     * Creates new form HalamanUI
     */
    public HalamanUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbuttonHome = new javax.swing.JButton();
        jButtonPengeluaran = new javax.swing.JButton();
        jButtonPemasukkan = new javax.swing.JButton();
        jButtonRiwayatTransaksi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jpHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPPengeluaran = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPPemasukkan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 800));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WALLET");

        jbuttonHome.setBackground(new java.awt.Color(0, 51, 153));
        jbuttonHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbuttonHome.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonHome.setText("Home");
        jbuttonHome.setBorderPainted(false);
        jbuttonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbuttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonHomeActionPerformed(evt);
            }
        });

        jButtonPengeluaran.setBackground(new java.awt.Color(0, 51, 153));
        jButtonPengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPengeluaran.setText("Pengeluaran");
        jButtonPengeluaran.setBorderPainted(false);
        jButtonPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPengeluaranActionPerformed(evt);
            }
        });

        jButtonPemasukkan.setBackground(new java.awt.Color(0, 51, 153));
        jButtonPemasukkan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPemasukkan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPemasukkan.setText("Pemasukkan");
        jButtonPemasukkan.setBorderPainted(false);
        jButtonPemasukkan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPemasukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPemasukkanActionPerformed(evt);
            }
        });

        jButtonRiwayatTransaksi.setBackground(new java.awt.Color(0, 51, 153));
        jButtonRiwayatTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonRiwayatTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRiwayatTransaksi.setText("Riwayat Transaksi");
        jButtonRiwayatTransaksi.setBorderPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPemasukkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRiwayatTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(jbuttonHome)
                .addGap(18, 18, 18)
                .addComponent(jButtonPengeluaran)
                .addGap(18, 18, 18)
                .addComponent(jButtonPemasukkan)
                .addGap(18, 18, 18)
                .addComponent(jButtonRiwayatTransaksi)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(1100, 800));

        jpHome.setBackground(new java.awt.Color(0, 0, 102));
        jpHome.setPreferredSize(new java.awt.Dimension(1100, 800));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Home");

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPengeluaran.setBackground(new java.awt.Color(0, 0, 102));
        jPPengeluaran.setPreferredSize(new java.awt.Dimension(1100, 800));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pengeluaran");

        javax.swing.GroupLayout jPPengeluaranLayout = new javax.swing.GroupLayout(jPPengeluaran);
        jPPengeluaran.setLayout(jPPengeluaranLayout);
        jPPengeluaranLayout.setHorizontalGroup(
            jPPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        jPPengeluaranLayout.setVerticalGroup(
            jPPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPengeluaranLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(914, Short.MAX_VALUE))
        );

        jPPemasukkan.setBackground(new java.awt.Color(0, 0, 102));
        jPPemasukkan.setPreferredSize(new java.awt.Dimension(1100, 800));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pemasukkan");

        javax.swing.GroupLayout jPPemasukkanLayout = new javax.swing.GroupLayout(jPPemasukkan);
        jPPemasukkan.setLayout(jPPemasukkanLayout);
        jPPemasukkanLayout.setHorizontalGroup(
            jPPemasukkanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPemasukkanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPPemasukkanLayout.setVerticalGroup(
            jPPemasukkanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPemasukkanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(931, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPPemasukkan, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPPemasukkan, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonHomeActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jpHome);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jbuttonHomeActionPerformed

    private void jButtonPemasukkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPemasukkanActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        jPanel3.add(jPPemasukkan);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButtonPemasukkanActionPerformed

    private void jButtonPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPengeluaranActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPPengeluaran);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButtonPengeluaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPemasukkan;
    private javax.swing.JButton jButtonPengeluaran;
    private javax.swing.JButton jButtonRiwayatTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPPemasukkan;
    private javax.swing.JPanel jPPengeluaran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbuttonHome;
    private javax.swing.JPanel jpHome;
    // End of variables declaration//GEN-END:variables
}
